version: '3.7'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 1s
      retries: 5

  qubit:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    command: main.py